#include "tjsCommHead.h"
#include "VorbisWaveDecoder.h"

#include "WaveIntf.h"
#include "TVPSystem.h"
#include "TVPStorage.h"
#include "TVPDebug.h"

#include "vorbis/vorbisfile.h"

static const bool FloatExtraction = false; // true if output format is IEEE 32-bit float

#define WARN_OLD_VORBIS_DATE 20020717
// warn if the stream is generated by old vorbis encoder earlier than this
#define WARN_PREFER_ENCODER_VERSION "Vorbis encoder 1.0 (dated 2002/07/17) or later is recommended."
static bool OldEncoderWarned = false;
// static LONG AllocCount = 0; // memory block allocation count for decoder

// static bool Look_Replay_Gain = false; // whether to look replay gain information
// static bool Use_Album_Gain = false; // whether to use album gain, otherwise use track gain

class VorbisWaveDecoder : public tTVPWaveDecoder // decoder interface
{
    bool InputFileInit;            // whether InputFile is inited
    OggVorbis_File InputFile;      // OggVorbis_File instance
    tTJSBinaryStream* InputStream; // input stream
    tTVPWaveFormat Format;         // output PCM format
    int CurrentSection;            // current section in vorbis stream
    int pcmsize;

public:
    VorbisWaveDecoder() : InputFileInit(false), InputStream(nullptr), CurrentSection(-1)
    {
        pcmsize = FloatExtraction ? 4 : 2;
    }
    ~VorbisWaveDecoder()
    {
        if (InputFileInit)
        {
            ov_clear(&InputFile);
            InputFileInit = false;
        }
        if (InputStream)
        {
            delete InputStream;
        }
    }

public:
    // ITSSWaveDecoder
    virtual void GetFormat(tTVPWaveFormat& format) { format = Format; }
    virtual bool Render(void* buf, tjs_uint bufsamplelen, tjs_uint& rendered);
    virtual bool SetPosition(tjs_uint64 samplepos);
    virtual bool DesiredFormat(const tTVPWaveFormat& format)
    {
        if (format.IsFloat == Format.IsFloat)
            return false;
        if (format.IsFloat)
        {
            pcmsize = 4;
            Format.IsFloat = true;
            Format.BitsPerSample = 32;
            Format.BytesPerSample = 4;
        }
        else
        {
            pcmsize = 2;
            Format.IsFloat = false;
            Format.BitsPerSample = 16;
            Format.BytesPerSample = 2;
        }
        return true;
    }

    // others
    bool SetStream(const ttstr& storagename);

private:
    size_t static read_func(void* ptr, size_t size, size_t nmemb, void* datasource)
    {
        VorbisWaveDecoder* decoder = (VorbisWaveDecoder*)datasource;
        if (!decoder->InputStream)
            return 0;
        return decoder->InputStream->Read(ptr, size * nmemb) / size;
    }
    int static seek_func(void* datasource, ogg_int64_t offset, int whence)
    {
        VorbisWaveDecoder* decoder = (VorbisWaveDecoder*)datasource;
        if (!decoder->InputStream)
            return -1;

        tjs_uint64 result;
        int seek_type = TJS_BS_SEEK_SET;

        switch (whence)
        {
            case SEEK_SET:
                seek_type = TJS_BS_SEEK_SET;
                break;
            case SEEK_CUR:
                seek_type = TJS_BS_SEEK_CUR;
                break;
            case SEEK_END:
                seek_type = TJS_BS_SEEK_END;
                break;
        }

        result = decoder->InputStream->Seek(offset, seek_type);
        return 0;
    }
    int static close_func(void* datasource)
    {
        VorbisWaveDecoder* decoder = (VorbisWaveDecoder*)datasource;
        if (!decoder->InputStream)
            return EOF;
        delete decoder->InputStream;
        decoder->InputStream = NULL;
        return 0;
    }
    long static tell_func(void* datasource)
    {
        VorbisWaveDecoder* decoder = (VorbisWaveDecoder*)datasource;
        if (!decoder->InputStream)
            return EOF;
        return decoder->InputStream->Seek(0, TJS_BS_SEEK_CUR);
    }
};

tTVPWaveDecoder* VorbisWaveDecoderCreator::Create(const ttstr& storagename, const ttstr& extension)
{
    static ttstr strext = TJS_N(".ogg");
    VorbisWaveDecoder* decoder = nullptr;
    if (extension == strext)
    {
        decoder = new VorbisWaveDecoder();
        if (!decoder->SetStream(storagename))
        {
            delete decoder;
            decoder = nullptr;
        }
    }
    return decoder;
}

bool VorbisWaveDecoder::Render(void* buf, tjs_uint bufsamplelen, tjs_uint& rendered)
{
    // render output PCM
    if (!InputFileInit)
        return false; // InputFile is yet not inited

    int pos = 0; // decoded PCM (in bytes)
    if (Format.IsFloat)
    {
        int remain = bufsamplelen;
        float* p = (float*)buf;
        while (remain)
        {
            // float *p = (float*)buf;
            int samples;
            do
            {
                float** pcm;
                int current_section;
                samples = ov_read_float(&InputFile, &pcm, remain, &current_section);
                for (int j = 0; j < samples; j++)
                    for (int i = 0; i < Format.Channels; i++)
                    {
                        *p++ = pcm[i][j];
                    }
            } while (samples < 0); // ov_read would return a negative number
            // if the decoding is not ready
            if (samples == 0)
                break;
            pos += samples;
            remain -= samples;
        }
    }
    else
    {
        int remain = bufsamplelen * Format.Channels * pcmsize; // remaining PCM (in bytes)
        while (remain)
        {
            int res;
            do
            {
                res = ov_read(&InputFile, ((char*)buf + pos), remain, 0, pcmsize, 1,
                              &CurrentSection); // decode via ov_read
            } while (res < 0);                  // ov_read would return a negative number
            // if the decoding is not ready
            if (res == 0)
                break;
            pos += res;
            remain -= res;
        }
        pos /= (Format.Channels * pcmsize); // convert to PCM position
    }

    rendered = pos; // return rendered PCM samples

    return (unsigned int)pos >= bufsamplelen; // if the decoding is ended
}

bool VorbisWaveDecoder::SetPosition(tjs_uint64 samplepos)
{
    // set PCM position (seek)
    if (!InputFileInit)
        return false;

    if (0 != ov_pcm_seek(&InputFile, samplepos))
    {
        return false;
    }

    return true;
}

bool VorbisWaveDecoder::SetStream(const ttstr& url)
{
    // set input stream
    InputStream = TVPCreateStream(url, TJS_BS_READ);
    if (!InputStream)
        return false;

    ov_callbacks callbacks = {read_func, seek_func, close_func, tell_func};
    // callback functions

    // open input stream via ov_open_callbacks
    if (ov_open_callbacks(this, &InputFile, NULL, 0, callbacks) < 0)
    {
        // error!
        delete InputStream;
        InputStream = NULL;
        return false;
    }

    InputFileInit = true;

    // retrieve PCM information
    vorbis_info* vi;
    vi = ov_info(&InputFile, -1);
    if (!vi)
    {
        return false;
    }

    // set Format up
    Format.BitsPerSample = FloatExtraction ? 32 : 16;
    Format.BytesPerSample = Format.BitsPerSample / 8;
    Format.Channels = vi->channels;
    Format.IsFloat = FloatExtraction;
    Format.SamplesPerSec = vi->rate;
    Format.Seekable = true;
    Format.SpeakerConfig = 0;
    //	Format.Signed = true;
    //	Format.BigEndian = false;

    ogg_int64_t pcmtotal = ov_pcm_total(&InputFile, -1); // PCM total samples
    if (pcmtotal < 0)
        pcmtotal = 0;
    Format.TotalSamples = pcmtotal;

    double timetotal = ov_time_total(&InputFile, -1); // total time in sec.
    if (timetotal < 0)
        Format.TotalTime = 0;
    else
        Format.TotalTime = timetotal * 1000.0;

    // check old vorbis stream, which is generated by old encoder.
    if (!OldEncoderWarned)
    {
        vorbis_comment* vc = ov_comment(&InputFile, -1);
        if (vc->vendor)
        {
            const char* vorbis_date = strstr(vc->vendor, "libVorbis I ");
            if (vorbis_date)
            {
                int date = atoi(vorbis_date + 12);
                if (date < WARN_OLD_VORBIS_DATE)
                {
                    OldEncoderWarned = true;
                    TVPAddLog(TJS_N("wuvorbis: warning: The Vorbis stream \"") + ttstr(url) +
                              TJS_N("\" seems to be generated by old Vorbis encoder [") +
                              ttstr(vc->vendor) +
                              TJS_N("]. Check that your encoder is new enough, unless you prefer "
                                    "the old encoder. The old stream can still be decoded, but ") +
                              ttstr(WARN_PREFER_ENCODER_VERSION));
                }
            }
        }
    }

    return true;
}